export const environment = {
  production: true,
  KENDO_UI_LICENSE: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkxJQyJ9.eyJwcm9kdWN0cyI6W3sidHJpYWwiOmZhbHNlLCJjb2RlIjoiS0VORE9VSVJFQUNUIiwibGljZW5zZUV4cGlyYXRpb25EYXRlIjoxNzU0MzA4Njk0fSx7InRyaWFsIjpmYWxzZSwiY29kZSI6IktFTkRPVUlDT01QTEVURSIsImxpY2Vuc2VFeHBpcmF0aW9uRGF0ZSI6MTc1NDMwODY5NH0seyJ0cmlhbCI6ZmFsc2UsImNvZGUiOiJLRU5ET1VJVlVFIiwibGljZW5zZUV4cGlyYXRpb25EYXRlIjoxNzU0MzA4Njk0fSx7InRyaWFsIjpmYWxzZSwiY29kZSI6IktFTkRPVUlBTkdVTEFSIiwibGljZW5zZUV4cGlyYXRpb25EYXRlIjoxNzU0MzA4Njk0fV0sImludGVncml0eSI6IllcL1wvc1wvVE56TnAzOXRnbVBqZTVJcTFHcTB3Yz0iLCJsaWNlbnNlSG9sZGVyIjoidGF1c2VlZi5hbGFtQGttZ3VzLmNvbSIsImlhdCI6MTcyOTI0MTg4NywiYXVkIjoidGF1c2VlZi5hbGFtQGttZ3VzLmNvbSIsInVzZXJJZCI6ImE2ODY5NmE4LTVlMjYtNDU2ZC1hNmRmLWIxNzRiMzRmNWFmZSJ9.0vRGNnMUvCBAz8Weyc0sbJ6nyUZc_KYUyDom1LEReMIetMkqXpEKmjHuyTlSzzhHik5H4SBHQFrnPfcev8FUiRQKjDottD6ce1btZpHm0ntWcT2zZBZxmcMuLhO5JTsXpki-PNiIQ189dHcof3bTyZYsXitLLfI0ovZUtdRKFb-im4bYsikQM19IRYUfdkExSofxcG58yQV2VCgwpGKihqZSfab_zkDOBkYp5scaMFST2vrPZp3j6c4HhpaOvNla3VUK-YvFw0MugPcmfV7AyY9WrgcRH-9zyfeGwA7MwcRIPiuT7LhcRCfReMqcBoASf2EwpnhAlCHQhHMqZKxUpA',
  API_ENDPOINT : 'https://www.myfpdportal.com/api/',
  googleMapsApiKey :'https://maps.googleapis.com/maps/api/js?key=AIzaSyAdUgE8ukMztrdAmTRQ836vZgkgK2OJtRI&callback=initMap',
  AI_UIENDPOINT : 'https://aiapp.fpdsolutions.com/#/',
};
