export interface AgencyAdmin {
    // userId: number;
    // agencyId: number;
    // managerId: number;
    // manager: string | null;
    // supervisorId: number;
    // supervisor: string | null;
    // isActive: true;
    // agentName: string | null;
    // registered: "Yes" | "No";
    // agencyName: string;
    // contactPerson: string;
    // phoneCell: number | null;
    // phoneHome: number | null;
    // phoneOffice: number | null;
    // fax: number | null;
    // email: string;
    // npn: number;
    // npnExpirationDate: Date;
    // addressLine1: string;
    // addressLine2:string ;
    // city: string;
    // state: string;
    // zip: number;
    // createdBy: number;
    // createdOn: Date;
    // modifiedBy: number;
    // modifiedOn: Date;
    // correlationId: string | null;
    // auditableRequestId: string | null;
    // auditableRequestName: string | null;
    // auditableSourceEventName: string | null;
    // createdDateTime: Date;
    // updatedBy: string | null;
    // updatedDateTime: Date;
    // updateReason: string | null;
    // ownerId: string | null;
    // isDeleted: boolean;
    // isApproved: false;
    // approverId: string | null;
    // approvedDateTime: string | null;
    // isAuthorized: string | null;
    // authorizedById: string | null;
    // authorizedDateTime: string | null;
    // sysData: string | null;
    // tenantId: string | null;
    // subTenantId: string | null
    userId: number;
    agencyId: number;
    managerId: number;
    manager?: any;
    supervisorId: number;
    supervisor?: any;
    isActive: boolean;
    agentName?: any;
    agencyName: string;
    contactPerson: string;
    phoneCell: string;
    phoneHome: string;
    phoneOffice: string;
    fax: string;
    email: string;
    npn: string;
    npnExpirationDate: Date;
    addressLine1: string;
    addressLine2: string;
    city: string;
    state: string;
    zip: string;
    createdBy: number;
    createdOn: Date;
    modifiedBy: number;
    modifiedOn: Date;
    registered: string;
}