export interface Quote {
    quoteId: number,
    ref: string,
    indicationNumber: string,
    quoteNumber: string,
    underwriterQuoteId: number,
    lobId: number,
    lob: string,
    lobDescription: string,
    transactionId: number,
    transactionCode: string,
    agentId: number,
    agentName: string,
    agencyName: string,
    email: string,
    phone: string,
    yearsInsured: number,
    alfredFlagsId: number,
    effectiveDate: string,
    effective_Date: string,
    expiryDate: string,
    expiry_Date: string,
    indicationDate: string,
    stage: number,
    stageId: string,
    premium: number,
    stateID: number,
    state: string,
    underwriterID: number,
    underwriter: string,
    underwriterAssistantID: number,
    underwriterAssistant:string,
    processingTypeID: number,
    processingType: string,
    carrierID: number,
    carrier: string,
    isOpenTask: boolean,
    isActive: boolean,
    createdOn: string,
    insuredID: number,
    insuredName:string,
    website: string,
    comments:string,
    alerts: [],
    stages: [
        {
            quoteId: number,
            quoteNumber: string,
            effective_Date: string,
            expiry_Date: string,
            transactionCode: string,
            status: string,
            isActive: true,
            renewalDate: string,
            renewal_Date: string,
            endorsementDate: string,
            endorsement_Date: string,
            cancelDate: string,
            cancel_Date: string,
            created_Date: string,
            premium: number,
            refundPremium: number,
            pendingRenewal: boolean,
            allowCancel: boolean,
            allowEndorsement: boolean
        }
    ],
    underwriterAssistants: []
}
