name: DeploymentFPDAppToGitHubPages
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate Node version
        run: node -v

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps 

      - name: Build app
        run: npm run build -- --configuration production --base-href /AngularQuesCICD/


      - name: Archive production artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: dist/adjuster-locator-app   # adjust if build output folder is different

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show deployment URL
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"





